### ISSUE TITLE
Could not resolve specified command executor YOUR EXECUTOR as a valid file path or a class named any of bpipe.executor.YOUR EXECUTOR

### ISSUE THREAD

**Issue by mariakondili** [Oshlack/Slinker#7]
Hello, 
I have this issue for quiet a few days now, I cannot find out where the problem is !
Here is my script for running Slinker, after cloning the repo. I am launching in a cluster, after creating a private conda environment. 

The environment created as follows : 

Added following lines  @  ~/.condarc

```
envs_dirs:
  - /shared/projects/<project_name>/conda/env
pkgs_dirs:
  - /shared/projects/<project_name>/conda/pkgs
```

 And then ...

`$ conda env create --file Slinker/env/slinker.yml`

The script : 

``` 
#SBATCH --cpus-per-task 4 
module load java-jdk/11.0.9.1
export java=/soft/miniconda/envs/java-jdk-11.0.9.1/bin/java  #because I was getting error "java: not found"
export bpipe=/projects/Slinker/tools/bpipe-0.9.9.9/bin/bpipe
SLINKERDIR=/projects/Slinker
work_dir=/projects/run_slinker

bpipe -p case_sample=${SLINKERDIR}/tests/unhealthy_Aligned.sortedByCoord.out.bam \
 -p gene=ETV6 -p genome=19 -p a_mem=20000000000 -p g_mem=20000000000 \
 -p results=${work_dir}/test_results/  -p threads=4  ${SLINKERDIR}/workflows/slinker.groovy ${SLINKERDIR}/tests/*.bam
 
```

the  slurm.out file reports: 

```
| Starting Pipeline at 2022-08-19 16:20  |

Stage make_dir (cases) 
ERROR: stage make_dir failed: Could not resolve specified command executor YOUR EXECUTOR as a valid file path or a class named any of bpipe.executor.YOUR EXECUTOR, bpipe.executor.YOUR EXECUTORCommandExecutor, YOUR EXECUTOR


= Pipeline Failed =

One or more parallel stages aborted. The following messages were reported:
--------------------------------------- make_dir  ( cases )  ---------------------------------------
Could not resolve specified command executor YOUR EXECUTOR as a valid file path or a class named any of bpipe.executor.YOUR EXECUTOR, bpipe.executor.YOUR EXECUTORCommandExecutor, YOUR EXECUTOR

----------------------------------------------------------------------------------------------------
Use 'bpipe errors' to see output from failed commands.
```

"bpipe errors" shows : 
```
======================== Found 0 failed commands from run []======================== 
```` 

..but before that, I would get same message with "Pipeline failed" and in "bpipe_errors" : `java not found.` 
So ,after I added the path of java executable I only have the "pipe failed" message and I cannot find where the command "YOUR EXECUTOR" refers to !  
Concerning the make_dir, the test_results/ directory can be created, it is in my projects-path and i have rights to create.

**Comment by breons** [comment]
Hello!

So, that particular area in bpipe.config is referring to setting up Slinker (through bpipe) to work in your cluster environment:
https://docs.bpipe.org/Guides/ResourceManagers/

If you're not running slinker on a cluster you should be able to just remove everything within "cluster configuration" in workflow/bpipe.config

Hopefully that gets you running!

**Comment by mariakondili** [comment]
Thanks ! I actually am running in cluster, so I added `executor="slurm"` & `queue="fast"` for my cluster's architecture, and it worked !
